PID = "PID"
TRIAL_COUNT = "TRIAL COUNT"
SELF_LIE = "SELF LIE"
SELF_TRUE = "SELF TRUE"
OTHER_LIE = "OTHER LIE"
OTHER_TRUTH = "OTHER TRUTH"
RT = "RT"
YOU_ON_TOP = "YOU ON TOP"
LIE_POSITION = "LIE POSITION"
TRUTH_POSITION = "TRUTH POSITION"
SELECTION = "SELECTION"
SCREEN_WIDTH = "SCREEN WIDTH"
MOUSE_COORD = "MOUSE COORD"

PROLIFIC_ID = "PROLIFIC ID"
GAME = "GAME"
BLOCK = "BLOCK"
TRIAL_INDEX = "TRIAL INDEX"

MOUSE_TIMESTAMP = "MOUSE TIMESTAMP"
MOUSE_X = "MOUSE X"
MOUSE_Y = "MOUSE Y"

AOI = "AOI"
FIRST_AOI = "FIRST AOI"
LAST_AOI = "LAST AOI"
N_AOIS = "N AOIS"
UNIQUE_AOIS = "UNIQUE AOIS"
N_ALT_TRANSITIONS, N_ATT_TRANSITIONS = "N ALT TRANSITIONS", "N ATT TRANSITIONS"
N_TRANSITIONS = "N TRANSITIONS"

LIE = "LIE"
TRUTH = "TRUTH"
OTHER = "OTHER"

SELECTED_AOI = "SELECTED AOI"
DWELL_TIME = "DWELL TIME"

IS_LIE = "IS LIE"
IS_TRUTH = "IS TRUTH"
IS_OTHER = "IS OTHER"

CLUSTER = "CLUSTER"

DWELL_COLUMNS = [SELF_LIE, SELF_TRUE, OTHER_LIE, OTHER_TRUTH]

PID_1, PID_2 = "PID 1", "PID 2"
TRIAL_1, TRIAL_2 = "TRIAL 1", "TRIAL 2"
DISTANCE = "DISTANCE"
PATH = "PATH"
SELECTED_AOI_1, SELECTED_AOI_2 = "SELECTED AOI 1", "SELECTED AOI 2"

AVG_DWELL = "AVG DWELL"
PAYNE_INDEX = "PAYNE INDEX"
TRIAL = "TRIAL"

TRIAL_ID = "TRIAL ID"
TRIAL_ID_1, TRIAL_ID_2 = "TRIAL ID 1", "TRIAL ID 2"
TRIAL_COUNT_1, TRIAL_COUNT_2 = "TRIAL COUNT 1", "TRIAL COUNT 2"

MEAN, VARIANCE = "MEAN", "VARIANCE"
PSEUDO_F = "PSEUDO F"
N_CLUSTER = "N CLUSTER"

DWELL_TIME_MS = "DWELL TIME MS"

SILHOUETTE = "SILHOUETTE"

SELF_GAIN = "SELF GAIN"
OTHER_LOSS = "OTHER LOSS"

GAIN_OF_TEN = "+10 SELF GAIN"
GAIN_UNDER_TEN = "> 10 SELF GAIN"
